cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

language: android

jdk:
  - oraclejdk8

# todo: remove once https://github.com/travis-ci/travis-ci/issues/8874 is resolved
before_install:
  - yes | sdkmanager "platforms;android-28"

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-28

    # Additional components:
    - extra-android-m2repository

branches:
  only:
    - main
    # Match semver branch names like 1.0.0, 1.0.0-rc.2, etc.:
    - /^\d+\.\d+\.\d+(?:-rc\.\d+)?$/

script: ./travis-build.sh
